### ISSUE TITLE
consecutive SC failure

### ISSUE THREAD

**Issue by lifukang** [darchr/Keystone-experiments#1]
Hello，it’s my pleasure to use this tool and i completely launched the env with the lauch file.But I want to know whether a error happened when my screen  displayed “consecutive SC failure” after run 2 hours.This is my command """:build/RISCV/gem5.opt  /home/kang/Keystone-experiments-main/configs-keystone-default/run_trusted.py /home/kang/keystone/build/sm.build/platform/generic/firmware/fw_payload.elf /home/kang/keystone/build/buildroot.build/images/rootfs.ext2 timing 1 aes.O3"""

Thank you.
Kang

**Comment by powerjg** [comment]
Hello,

`consecutive SC failure` warnings are not indicative of any problems. I would check the serial terminal output in `m5out/` to see if progress is being made through the booting process. Don't expect gem5 to be fast. It should take order hours to boot linux and start your application. Typically, 1 simulated second takes about 1 day (24 hour).

**Comment by lifukang** [comment]
Thank you very much , I will try and after trying i will give a comment here.
