### ISSUE TITLE
Array subscript out of bounds in vpc_open function of vpc.c when building components

### ISSUE THREAD

**Issue by AlfiRam** [darchr/Keystone-experiments#2]
## Description
When compiling the vpc.c file (running `make` command), array subscript warnings are treated as errors, which causes the build to fail. The warnings indicate that there are potential out-of-bounds accesses to the `buf` array which is used for reading and manipulating VHD headers.

## Error Messages
![image](https://github.com/darchr/Keystone-experiments/assets/89893674/676617bd-3e5b-45c0-a7b3-e188a15f9565)

Any help or guidance on how to address these out-of-bounds accesses would be greatly appreciated.

**Comment by AlfiRam** [comment]
is it safe to just `make CFLAGS="-Wno-array-bounds"` ?

**Comment by jonghyunL** [comment]
Did you get a solution on this?
